import { 
  ImageIcon, 
  FileText, 
  BarChart3, 
  Link2, 
  Hash,
  Wand2,
  Sparkles,
  PenTool,
  RefreshCw,
  Globe,
  Zap,
  Target,
  TrendingUp,
  Camera,
  Palette,
  Bot,
  ClipboardCheck,
  Brain,
  KeyRound,
  Eye,
  Gauge,
  Type,
  Code,
  Mic,
  FileCode,
  ScanSearch,
  ShieldCheck,
  FileJson,
  MapPin,
  Tags,
  Eraser,
  MessageSquare,
  Calculator,
  Clock,
  ArrowUpFromLine,
  Minimize2,
  RotateCcw,
  ShieldOff,
  Layers,
  Scissors,
  Expand,
  AlignLeft,
  Activity,
  Users,
  LucideIcon
} from "lucide-react"

export type ToolCategory = "image" | "seo" | "writing" | "analytics" | "utility" | "agents"
export type ToolTier = "Free" | "Pro"
export type ToolType = "text" | "image"

export interface Tool {
  id: number
  name: string
  description: string
  longDescription: string
  icon: LucideIcon
  category: ToolCategory
  tier: ToolTier
  slug: string
  type: ToolType
  placeholder?: string
  settings?: {
    label: string
    type: "select" | "slider" | "toggle"
    options?: string[]
    min?: number
    max?: number
    default?: string | number | boolean
  }[]
}

export const tools: Tool[] = [
  // IMAGE TOOLS (9) - Free
  {
    id: 1,
    name: "AI Image Generator",
    description: "Generate images from text prompts",
    longDescription: "Transform your ideas into stunning visuals with our AI-powered image generator. Simply describe what you want to create, and watch as AI brings your vision to life in seconds.",
    icon: ImageIcon,
    category: "image",
    tier: "Free",
    slug: "ai-image-generator",
    type: "image",
    placeholder: "A futuristic city at sunset with flying cars...",
    settings: [
      { label: "Style", type: "select", options: ["Realistic", "Anime", "Digital Art", "Oil Painting", "Watercolor", "3D Render"], default: "Realistic" },
      { label: "Aspect Ratio", type: "select", options: ["1:1", "16:9", "9:16", "4:3"], default: "1:1" },
    ],
  },
  {
    id: 2,
    name: "Image Compressor",
    description: "Reduce image size without quality loss",
    longDescription: "Optimize your images for the web without sacrificing visual quality. Our smart compression algorithm reduces file sizes by up to 80% while maintaining crystal-clear images.",
    icon: Minimize2,
    category: "image",
    tier: "Free",
    slug: "image-compressor",
    type: "image",
    settings: [
      { label: "Quality", type: "slider", min: 10, max: 100, default: 80 },
      { label: "Output Format", type: "select", options: ["Same as input", "JPEG", "PNG", "WebP"], default: "Same as input" },
    ],
  },
  {
    id: 3,
    name: "Image Format Converter",
    description: "Convert JPG PNG WebP AVIF instantly",
    longDescription: "Instantly convert between image formats including JPG, PNG, WebP, and AVIF. Perfect for optimizing images for different platforms and use cases.",
    icon: RefreshCw,
    category: "image",
    tier: "Free",
    slug: "image-format-converter",
    type: "image",
    settings: [
      { label: "Output Format", type: "select", options: ["JPEG", "PNG", "WebP", "AVIF", "GIF"], default: "WebP" },
      { label: "Quality", type: "slider", min: 10, max: 100, default: 85 },
    ],
  },
  {
    id: 4,
    name: "Background Remover",
    description: "Remove image background with AI",
    longDescription: "Automatically remove backgrounds from any image with AI precision. Perfect for product photos, portraits, and creating transparent PNGs.",
    icon: Camera,
    category: "image",
    tier: "Free",
    slug: "background-remover",
    type: "image",
    settings: [
      { label: "Edge Refinement", type: "select", options: ["Auto", "Sharp", "Smooth", "Feathered"], default: "Auto" },
      { label: "Output Format", type: "select", options: ["PNG", "WebP"], default: "PNG" },
    ],
  },
  {
    id: 5,
    name: "Image Upscaler",
    description: "Upscale image to 4x resolution with AI",
    longDescription: "Enhance image resolution up to 4x using advanced AI technology. Restore details, reduce noise, and make your images print-ready.",
    icon: ArrowUpFromLine,
    category: "image",
    tier: "Free",
    slug: "image-upscaler",
    type: "image",
    settings: [
      { label: "Scale", type: "select", options: ["2x", "3x", "4x"], default: "2x" },
      { label: "Denoise", type: "toggle", default: true },
      { label: "Face Enhancement", type: "toggle", default: false },
    ],
  },
  {
    id: 6,
    name: "AI Image Detector",
    description: "Detect if image is AI generated",
    longDescription: "Analyze images to determine if they were created by AI. Our detector identifies patterns and artifacts common in AI-generated content.",
    icon: ScanSearch,
    category: "image",
    tier: "Free",
    slug: "ai-image-detector",
    type: "image",
    settings: [
      { label: "Analysis Depth", type: "select", options: ["Quick", "Standard", "Deep"], default: "Standard" },
    ],
  },
  {
    id: 7,
    name: "Watermark Remover",
    description: "Remove SynthID Gemini ChatGPT watermarks",
    longDescription: "Remove visible and invisible watermarks from images including SynthID, Gemini, and ChatGPT watermarks. Clean up your images professionally.",
    icon: Eraser,
    category: "image",
    tier: "Free",
    slug: "watermark-remover",
    type: "image",
    settings: [
      { label: "Detection Mode", type: "select", options: ["Auto", "Visible Only", "Invisible Only", "Both"], default: "Auto" },
    ],
  },
  {
    id: 8,
    name: "Blog Image Generator",
    description: "Generate SEO optimized blog cover images",
    longDescription: "Create eye-catching blog cover images optimized for SEO. Add text overlays, choose from templates, and generate images that drive clicks.",
    icon: Layers,
    category: "image",
    tier: "Free",
    slug: "blog-image-generator",
    type: "image",
    placeholder: "Enter your blog title...",
    settings: [
      { label: "Style", type: "select", options: ["Modern", "Minimal", "Bold", "Professional", "Creative"], default: "Modern" },
      { label: "Dimensions", type: "select", options: ["1200x630 (OG)", "1920x1080 (HD)", "800x400 (Blog)"], default: "1200x630 (OG)" },
    ],
  },
  {
    id: 9,
    name: "Alt Text Generator",
    description: "Generate SEO friendly alt text for images",
    longDescription: "Automatically generate descriptive, SEO-optimized alt text for your images. Improve accessibility and search engine visibility.",
    icon: Type,
    category: "image",
    tier: "Free",
    slug: "alt-text-generator",
    type: "image",
    settings: [
      { label: "Length", type: "select", options: ["Short", "Medium", "Detailed"], default: "Medium" },
      { label: "Include Keywords", type: "toggle", default: true },
    ],
  },

  // SEO TOOLS (17)
  {
    id: 10,
    name: "SEO Agent",
    description: "24/7 automated SEO specialist",
    longDescription: "Your AI-powered SEO specialist that works around the clock. Automatically monitors rankings, identifies opportunities, and provides actionable recommendations.",
    icon: Bot,
    category: "seo",
    tier: "Pro",
    slug: "seo-agent",
    type: "text",
    placeholder: "Enter your website URL to start SEO analysis...",
    settings: [
      { label: "Analysis Frequency", type: "select", options: ["Daily", "Weekly", "Monthly"], default: "Weekly" },
      { label: "Monitor Competitors", type: "toggle", default: true },
    ],
  },
  {
    id: 11,
    name: "SEO Audit",
    description: "Full site audit 47+ issues checked",
    longDescription: "Comprehensive technical SEO audit that checks 47+ common issues. Get actionable insights to improve your site performance and rankings.",
    icon: ClipboardCheck,
    category: "seo",
    tier: "Free",
    slug: "seo-audit",
    type: "text",
    placeholder: "Enter your website URL for a complete SEO audit...",
    settings: [
      { label: "Crawl Depth", type: "select", options: ["Homepage Only", "10 Pages", "50 Pages", "Full Site"], default: "10 Pages" },
      { label: "Check Mobile", type: "toggle", default: true },
    ],
  },
  {
    id: 12,
    name: "AI Grader",
    description: "Score content for AI search visibility",
    longDescription: "Evaluate how well your content performs in AI-powered search engines. Get a score and recommendations to improve visibility in ChatGPT, Gemini, and more.",
    icon: Brain,
    category: "seo",
    tier: "Free",
    slug: "ai-grader",
    type: "text",
    placeholder: "Paste your content here to analyze AI search visibility...",
    settings: [
      { label: "Target AI", type: "select", options: ["All", "ChatGPT", "Gemini", "Claude", "Perplexity"], default: "All" },
    ],
  },
  {
    id: 13,
    name: "LLM Optimizer",
    description: "Optimize content for AI systems",
    longDescription: "Optimize your content to rank better in AI-powered systems. Restructure, enhance, and format your content for maximum LLM visibility.",
    icon: Sparkles,
    category: "seo",
    tier: "Pro",
    slug: "llm-optimizer",
    type: "text",
    placeholder: "Paste your content to optimize for LLMs...",
    settings: [
      { label: "Optimization Level", type: "select", options: ["Light", "Moderate", "Aggressive"], default: "Moderate" },
      { label: "Preserve Tone", type: "toggle", default: true },
    ],
  },
  {
    id: 14,
    name: "Keyword Rank Checker",
    description: "Check exact Google keyword positions",
    longDescription: "Check your exact ranking position for any keyword on Google. Track multiple keywords and compare against competitors.",
    icon: KeyRound,
    category: "seo",
    tier: "Free",
    slug: "keyword-rank-checker",
    type: "text",
    placeholder: "Enter your keyword and domain...",
    settings: [
      { label: "Location", type: "select", options: ["United States", "United Kingdom", "Canada", "Australia", "Global"], default: "United States" },
      { label: "Device", type: "select", options: ["Desktop", "Mobile", "Both"], default: "Desktop" },
    ],
  },
  {
    id: 15,
    name: "Competitor Keywords",
    description: "Reveal competitor top keywords",
    longDescription: "Discover the keywords your competitors rank for. Find gaps in your strategy and uncover new opportunities to outrank them.",
    icon: Eye,
    category: "seo",
    tier: "Pro",
    slug: "competitor-keywords",
    type: "text",
    placeholder: "Enter competitor website URL...",
    settings: [
      { label: "Results", type: "select", options: ["Top 10", "Top 50", "Top 100", "All"], default: "Top 50" },
      { label: "Include Paid", type: "toggle", default: false },
    ],
  },
  {
    id: 16,
    name: "SEO Ranking Checker",
    description: "Check website overall SEO performance",
    longDescription: "Get a comprehensive overview of your website SEO performance. Analyze domain authority, backlinks, organic traffic estimates, and more.",
    icon: Gauge,
    category: "seo",
    tier: "Free",
    slug: "seo-ranking-checker",
    type: "text",
    placeholder: "Enter website URL to check SEO ranking...",
  },
  {
    id: 17,
    name: "Keyword Density Checker",
    description: "Analyze keyword usage in content",
    longDescription: "Analyze keyword density and distribution in your content. Ensure optimal keyword usage without over-optimization.",
    icon: Target,
    category: "seo",
    tier: "Free",
    slug: "keyword-density-checker",
    type: "text",
    placeholder: "Paste your content to analyze keyword density...",
    settings: [
      { label: "Target Keyword", type: "select", options: ["Auto-detect", "Manual Entry"], default: "Auto-detect" },
    ],
  },
  {
    id: 18,
    name: "Schema Markup Generator",
    description: "Generate JSON-LD schema markup",
    longDescription: "Generate valid JSON-LD schema markup for rich snippets. Support for Article, Product, FAQ, How-to, and more schema types.",
    icon: Code,
    category: "seo",
    tier: "Free",
    slug: "schema-markup-generator",
    type: "text",
    placeholder: "Enter your content details to generate schema...",
    settings: [
      { label: "Schema Type", type: "select", options: ["Article", "Product", "FAQ", "How-to", "Local Business", "Event", "Recipe"], default: "Article" },
    ],
  },
  {
    id: 19,
    name: "GEO Optimization",
    description: "Generative engine optimization for AI search",
    longDescription: "Optimize your content for generative AI search engines. Ensure your content gets cited and featured in AI-generated responses.",
    icon: Globe,
    category: "seo",
    tier: "Pro",
    slug: "geo-optimization",
    type: "text",
    placeholder: "Paste your content for GEO optimization...",
  },
  {
    id: 20,
    name: "AEO Optimization",
    description: "Answer engine optimization for voice search",
    longDescription: "Optimize your content for voice search and answer engines. Structure content to appear in featured snippets and voice assistant responses.",
    icon: Mic,
    category: "seo",
    tier: "Pro",
    slug: "aeo-optimization",
    type: "text",
    placeholder: "Enter your content for voice search optimization...",
  },
  {
    id: 21,
    name: "LLMs.txt Generator",
    description: "Generate AI crawler instructions file",
    longDescription: "Generate an LLMs.txt file to instruct AI crawlers how to interact with your site. Control what content AI systems can access and use.",
    icon: FileCode,
    category: "seo",
    tier: "Free",
    slug: "llms-txt-generator",
    type: "text",
    placeholder: "Enter your website details to generate LLMs.txt...",
    settings: [
      { label: "Access Level", type: "select", options: ["Full Access", "Partial Access", "Restricted"], default: "Full Access" },
    ],
  },
  {
    id: 22,
    name: "Plagiarism Checker",
    description: "Scan content for duplicate text online",
    longDescription: "Check your content for plagiarism and duplicate text across the web. Ensure your content is original before publishing.",
    icon: ScanSearch,
    category: "seo",
    tier: "Free",
    slug: "plagiarism-checker",
    type: "text",
    placeholder: "Paste your content to check for plagiarism...",
    settings: [
      { label: "Check Depth", type: "select", options: ["Quick", "Standard", "Deep"], default: "Standard" },
    ],
  },
  {
    id: 23,
    name: "AI Detector",
    description: "Detect if content was written by AI",
    longDescription: "Analyze text to determine if it was written by AI. Our detector identifies patterns common in ChatGPT, Claude, and other AI writing.",
    icon: ShieldCheck,
    category: "seo",
    tier: "Free",
    slug: "ai-detector",
    type: "text",
    placeholder: "Paste text to check if it was written by AI...",
    settings: [
      { label: "Sensitivity", type: "select", options: ["Low", "Medium", "High"], default: "Medium" },
    ],
  },
  {
    id: 24,
    name: "Robots.txt Generator",
    description: "Generate robots.txt file for your site",
    longDescription: "Create a properly formatted robots.txt file for your website. Control crawler access and improve site indexing.",
    icon: FileJson,
    category: "seo",
    tier: "Free",
    slug: "robots-txt-generator",
    type: "text",
    placeholder: "Enter your website URL and crawl preferences...",
    settings: [
      { label: "Preset", type: "select", options: ["Allow All", "Block AI Crawlers", "Custom"], default: "Allow All" },
    ],
  },
  {
    id: 25,
    name: "XML Sitemap Generator",
    description: "Auto generate XML sitemap",
    longDescription: "Automatically generate an XML sitemap for your website. Help search engines discover and index all your pages efficiently.",
    icon: MapPin,
    category: "seo",
    tier: "Free",
    slug: "xml-sitemap-generator",
    type: "text",
    placeholder: "Enter your website URL to generate sitemap...",
    settings: [
      { label: "Frequency", type: "select", options: ["Daily", "Weekly", "Monthly", "Yearly"], default: "Weekly" },
      { label: "Priority", type: "select", options: ["Auto", "Manual"], default: "Auto" },
    ],
  },
  {
    id: 26,
    name: "Meta Tag Generator",
    description: "Generate SEO meta titles and descriptions",
    longDescription: "Create compelling meta titles and descriptions optimized for search engines. Improve click-through rates with AI-generated meta tags.",
    icon: Tags,
    category: "seo",
    tier: "Free",
    slug: "meta-tag-generator",
    type: "text",
    placeholder: "Enter your page content or topic...",
    settings: [
      { label: "Tone", type: "select", options: ["Professional", "Friendly", "Urgent", "Informative"], default: "Professional" },
      { label: "Include Keywords", type: "toggle", default: true },
    ],
  },

  // AI WRITING TOOLS (13)
  {
    id: 27,
    name: "AI Humanizer",
    description: "Make AI text sound human written",
    longDescription: "Transform AI-generated text into natural, human-sounding content. Bypass AI detection while maintaining quality and meaning.",
    icon: PenTool,
    category: "writing",
    tier: "Free",
    slug: "ai-humanizer",
    type: "text",
    placeholder: "Paste your AI-generated text here to humanize...",
    settings: [
      { label: "Humanization Level", type: "select", options: ["Light", "Medium", "Strong"], default: "Medium" },
      { label: "Preserve Formatting", type: "toggle", default: true },
    ],
  },
  {
    id: 28,
    name: "Outrank Article",
    description: "Write better article than competitors",
    longDescription: "Analyze top-ranking articles and generate content that outranks them. Our AI studies competitor content and creates superior articles.",
    icon: TrendingUp,
    category: "writing",
    tier: "Pro",
    slug: "outrank-article",
    type: "text",
    placeholder: "Enter the URL of the article you want to outrank...",
    settings: [
      { label: "Word Count", type: "select", options: ["1000", "1500", "2000", "3000", "5000"], default: "2000" },
      { label: "Include FAQ", type: "toggle", default: true },
    ],
  },
  {
    id: 29,
    name: "Topical Authority",
    description: "Build content cluster strategy",
    longDescription: "Create a comprehensive content cluster strategy to establish topical authority. Generate pillar pages and supporting content plans.",
    icon: Link2,
    category: "writing",
    tier: "Pro",
    slug: "topical-authority",
    type: "text",
    placeholder: "Enter your main topic to build a content cluster...",
    settings: [
      { label: "Cluster Size", type: "select", options: ["Small (5-10)", "Medium (10-20)", "Large (20-50)"], default: "Medium (10-20)" },
    ],
  },
  {
    id: 30,
    name: "Essay Extender",
    description: "Expand short essay with AI",
    longDescription: "Intelligently expand your essay while maintaining coherence and quality. Add depth, examples, and supporting arguments automatically.",
    icon: Expand,
    category: "writing",
    tier: "Free",
    slug: "essay-extender",
    type: "text",
    placeholder: "Paste your essay to expand...",
    settings: [
      { label: "Target Length", type: "select", options: ["25% longer", "50% longer", "Double"], default: "50% longer" },
      { label: "Add Citations", type: "toggle", default: false },
    ],
  },
  {
    id: 31,
    name: "Expand Sentence",
    description: "Expand single sentence to paragraph",
    longDescription: "Transform a single sentence into a fully developed paragraph. Add context, details, and supporting information automatically.",
    icon: AlignLeft,
    category: "writing",
    tier: "Free",
    slug: "expand-sentence",
    type: "text",
    placeholder: "Enter a sentence to expand into a paragraph...",
    settings: [
      { label: "Paragraph Length", type: "select", options: ["Short", "Medium", "Long"], default: "Medium" },
    ],
  },
  {
    id: 32,
    name: "Shorten Content",
    description: "Condense long content to shorter version",
    longDescription: "Intelligently condense long content while preserving key information. Perfect for creating summaries, abstracts, or concise versions.",
    icon: Scissors,
    category: "writing",
    tier: "Free",
    slug: "shorten-content",
    type: "text",
    placeholder: "Paste your content to shorten...",
    settings: [
      { label: "Target Length", type: "select", options: ["25%", "50%", "75%"], default: "50%" },
      { label: "Preserve Key Points", type: "toggle", default: true },
    ],
  },
  {
    id: 33,
    name: "Article Spinner",
    description: "Rewrite article in unique wording",
    longDescription: "Rewrite articles with completely unique wording while preserving meaning. Create multiple unique versions of the same content.",
    icon: RotateCcw,
    category: "writing",
    tier: "Free",
    slug: "article-spinner",
    type: "text",
    placeholder: "Paste your article to rewrite...",
    settings: [
      { label: "Uniqueness Level", type: "select", options: ["Low", "Medium", "High"], default: "Medium" },
      { label: "Versions", type: "select", options: ["1", "3", "5"], default: "1" },
    ],
  },
  {
    id: 34,
    name: "Bypass AI Detection",
    description: "Bypass GPTZero and AI detectors",
    longDescription: "Rewrite AI content to pass AI detection tools like GPTZero, Originality.ai, and others. Make your content undetectable.",
    icon: ShieldOff,
    category: "writing",
    tier: "Free",
    slug: "bypass-ai-detection",
    type: "text",
    placeholder: "Paste AI-generated text to make undetectable...",
    settings: [
      { label: "Bypass Strength", type: "select", options: ["Light", "Medium", "Strong"], default: "Strong" },
    ],
  },
  {
    id: 35,
    name: "Copywriting Templates",
    description: "50+ AIDA PAS ad copy templates",
    longDescription: "Access 50+ proven copywriting templates including AIDA, PAS, and more. Generate high-converting ad copy, emails, and landing pages.",
    icon: FileText,
    category: "writing",
    tier: "Free",
    slug: "copywriting-templates",
    type: "text",
    placeholder: "Describe your product or service...",
    settings: [
      { label: "Template", type: "select", options: ["AIDA", "PAS", "BAB", "4 Ps", "FAB", "ACCA"], default: "AIDA" },
      { label: "Tone", type: "select", options: ["Professional", "Casual", "Urgent", "Friendly"], default: "Professional" },
    ],
  },
  {
    id: 36,
    name: "AI Math Solver",
    description: "Solve any math problem step by step",
    longDescription: "Solve complex math problems with detailed step-by-step explanations. Supports algebra, calculus, statistics, and more.",
    icon: Calculator,
    category: "writing",
    tier: "Free",
    slug: "ai-math-solver",
    type: "text",
    placeholder: "Enter your math problem here...",
    settings: [
      { label: "Detail Level", type: "select", options: ["Basic", "Detailed", "Complete"], default: "Detailed" },
    ],
  },
  {
    id: 37,
    name: "Reddit Post Generator",
    description: "Generate viral Reddit posts",
    longDescription: "Create engaging Reddit posts optimized for specific subreddits. Generate titles, content, and follow Reddit best practices.",
    icon: MessageSquare,
    category: "writing",
    tier: "Free",
    slug: "reddit-post-generator",
    type: "text",
    placeholder: "Enter your topic and target subreddit...",
    settings: [
      { label: "Post Type", type: "select", options: ["Discussion", "Question", "Story", "Guide"], default: "Discussion" },
    ],
  },
  {
    id: 38,
    name: "Word Counter",
    description: "Count words characters and reading time",
    longDescription: "Count words, characters, sentences, paragraphs, and estimate reading time. Essential tool for content writers and editors.",
    icon: Clock,
    category: "writing",
    tier: "Free",
    slug: "word-counter",
    type: "text",
    placeholder: "Paste your text to count words...",
  },
  {
    id: 39,
    name: "Hashtag Generator",
    description: "Generate hashtags for social media",
    longDescription: "Generate relevant, trending hashtags for your social media posts. Optimize reach on Instagram, Twitter, TikTok, and more.",
    icon: Hash,
    category: "writing",
    tier: "Free",
    slug: "hashtag-generator",
    type: "text",
    placeholder: "Describe your post or enter keywords...",
    settings: [
      { label: "Platform", type: "select", options: ["Instagram", "Twitter", "TikTok", "LinkedIn", "All"], default: "All" },
      { label: "Count", type: "select", options: ["10", "20", "30"], default: "20" },
    ],
  },

  // ANALYTICS TOOLS (3) - Pro
  {
    id: 40,
    name: "Rank Tracker",
    description: "Monitor keyword rankings daily",
    longDescription: "Track your keyword rankings across search engines daily. Get alerts for ranking changes and comprehensive reporting.",
    icon: BarChart3,
    category: "analytics",
    tier: "Pro",
    slug: "rank-tracker",
    type: "text",
    placeholder: "Enter keywords and domain to track...",
    settings: [
      { label: "Tracking Frequency", type: "select", options: ["Daily", "Weekly"], default: "Daily" },
      { label: "Search Engine", type: "select", options: ["Google", "Bing", "Both"], default: "Google" },
    ],
  },
  {
    id: 41,
    name: "Backlink Analyzer",
    description: "Analyze and monitor backlink profile",
    longDescription: "Comprehensive backlink analysis and monitoring. Discover new backlinks, lost links, and analyze competitor backlink strategies.",
    icon: Link2,
    category: "analytics",
    tier: "Pro",
    slug: "backlink-analyzer",
    type: "text",
    placeholder: "Enter domain to analyze backlinks...",
    settings: [
      { label: "Analysis Depth", type: "select", options: ["Quick", "Standard", "Complete"], default: "Standard" },
    ],
  },
  {
    id: 42,
    name: "Traffic Analyzer",
    description: "Understand website traffic patterns",
    longDescription: "Analyze website traffic patterns, sources, and user behavior. Get insights into visitor demographics and engagement metrics.",
    icon: Activity,
    category: "analytics",
    tier: "Pro",
    slug: "traffic-analyzer",
    type: "text",
    placeholder: "Enter website URL to analyze traffic...",
  },

  // UTILITY TOOLS (3) - Free
  {
    id: 43,
    name: "Speed Optimizer",
    description: "Improve page load times Core Web Vitals",
    longDescription: "Analyze and optimize page load times and Core Web Vitals. Get actionable recommendations to improve website performance.",
    icon: Zap,
    category: "utility",
    tier: "Free",
    slug: "speed-optimizer",
    type: "text",
    placeholder: "Enter URL to analyze page speed...",
    settings: [
      { label: "Device", type: "select", options: ["Mobile", "Desktop", "Both"], default: "Both" },
    ],
  },
  {
    id: 44,
    name: "Color Palette",
    description: "Extract and generate color schemes",
    longDescription: "Extract colors from images or generate beautiful color palettes. Perfect for designers and brand consistency.",
    icon: Palette,
    category: "utility",
    tier: "Free",
    slug: "color-palette",
    type: "image",
    settings: [
      { label: "Palette Size", type: "select", options: ["3 Colors", "5 Colors", "8 Colors"], default: "5 Colors" },
      { label: "Mode", type: "select", options: ["Extract from Image", "Generate", "Complementary"], default: "Extract from Image" },
    ],
  },
  {
    id: 45,
    name: "Blog Outline",
    description: "Generate structured blog post outlines",
    longDescription: "Generate comprehensive blog post outlines with headings, subheadings, and key points. Perfect for planning content before writing.",
    icon: Wand2,
    category: "utility",
    tier: "Free",
    slug: "blog-outline",
    type: "text",
    placeholder: "Enter your blog topic or title...",
    settings: [
      { label: "Depth", type: "select", options: ["Basic", "Detailed", "Comprehensive"], default: "Detailed" },
      { label: "Include FAQ", type: "toggle", default: true },
    ],
  },

  // AGENTS (3) - Pro
  {
    id: 46,
    name: "SEO Agent Pro",
    description: "Automate entire SEO workflow 24/7",
    longDescription: "Your dedicated AI SEO agent that automates your entire SEO workflow. From audits to content recommendations, working 24/7.",
    icon: Bot,
    category: "agents",
    tier: "Pro",
    slug: "seo-agent-pro",
    type: "text",
    placeholder: "Enter your website to start automated SEO...",
  },
  {
    id: 47,
    name: "Reddit Agent",
    description: "Monitor and participate in Reddit threads",
    longDescription: "AI agent that monitors Reddit for relevant discussions and helps you participate authentically. Build brand presence on Reddit.",
    icon: MessageSquare,
    category: "agents",
    tier: "Pro",
    slug: "reddit-agent",
    type: "text",
    placeholder: "Enter subreddits and keywords to monitor...",
    settings: [
      { label: "Monitoring Mode", type: "select", options: ["Passive", "Active", "Engaged"], default: "Active" },
    ],
  },
  {
    id: 48,
    name: "Brand Monitor",
    description: "Track brand mentions in ChatGPT Gemini Claude",
    longDescription: "Monitor how AI systems mention your brand. Track citations in ChatGPT, Gemini, Claude, and other AI platforms.",
    icon: Users,
    category: "agents",
    tier: "Pro",
    slug: "brand-monitor",
    type: "text",
    placeholder: "Enter your brand name to monitor...",
    settings: [
      { label: "AI Platforms", type: "select", options: ["All", "ChatGPT Only", "Gemini Only", "Claude Only"], default: "All" },
      { label: "Alert Frequency", type: "select", options: ["Real-time", "Daily", "Weekly"], default: "Daily" },
    ],
  },
]

export function getToolBySlug(slug: string): Tool | undefined {
  return tools.find(tool => tool.slug === slug)
}

export function getToolsByCategory(category: ToolCategory): Tool[] {
  return tools.filter(tool => tool.category === category)
}
